<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Rsvp_Model_Rsvp extends Rsvp_Model_Base_Rsvp
{
	public function sendAlert(){
		//send alert email
		
		
		$to[] = $this->email;
		$to[] = 'ncaraccioli@cox.net';
		$to[] = 'caraccioli@cox.net';
		$host = 'caydi.info';
		$mail = new Zend_Mail();
		$mail->setFrom('noreply@'.$host, $host);
		foreach($to as $recipient) {
			$mail->addTo($recipient);
		}
		$subject = 'Rsvp Received';
		$mail->setSubject($subject);
		$txtBody = '';
		$txtBody .= <<<EOD
Name: {$this->first_name} {$this->last_name}
E-mail: {$this->email}
Comments:
{$this->comments}
EOD;
        $mail->setBodyText($txtBody);
        $mail->send();
    }
	
	
}
