<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class Rsvp_Model_Base_Rsvp extends Doctrine_Record
{
	public function setTableDefinition(){
	    $this->setTableName('rsvp');
		$this->hasColumn('id', 'integer', 11, array('type'=>'integer', 'length'=>11, 'primary' => true,'autoincrement' => true));
		$this->hasColumn('email', 'string', 255,array('type' => 'string','length' => 255));
		$this->hasColumn('first_name', 'string', 255,array('type' => 'string','length' => 255));
		$this->hasColumn('last_name', 'string', 255,array('type' => 'string','length' => 255));
		$this->hasColumn('number_of_people', 'string', 255,array('type' => 'string','length' => 255));
		$this->hasColumn('comments', 'string', null,array('type' => 'string'));
	}

	public function setUp(){
	    $this->actAs('Timestampable');
        $this->actAs('SoftDelete');
	}
}
