<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MediaGallery_Model_Media extends MediaGallery_Model_Base_Media
{
	
	public static $file_ext_to_type_map=array(
		'png'=>'photo',
		'gif'=>'photo',
		'jpg'=>'photo',
		'jpeg'=>'photo',
		'flv'=>'video',
		'wmv'=>'video',
		'mp3'=>'audio',
		'pdf'=>'pdf',
		'doc'=>'doc',
		'unknown'=>'unknown',
	);
    public static function getMediaTypeForFileName($filename){
        $ext = substr($filename,strrpos($filename, ".")+1);

    	$type = self::$file_ext_to_type_map[$ext];
    	$type = $type?$type:self::$file_ext_to_type_map['unknown'];
    	return $type;
    }
    
   
}
