<? $this->placeholder('title')->set('R.S.V.P Form'); ?>

<div id="rsvp-request-form-wrapper">
	<br />
	<p>
		Now <b>YOU</b> are invited to a Butterfly Ball,<br />
		So mark your calendars, and come one, come all...<br />
		It's not on the smooth Grass, by the side of a Wood,<br />
		But right here in your very own Neighborhood!<br />
		Girls will be Fairies, pretty tenants of air,<br />
		Boys will be Grasshoppers -- and all the other bugs there.<br />
		Please say you'll join us a we frolic and make merry<br />
		To celebrate Caydi's birthday wish to become a fairy...<br />
	</p>
	<?= $this->form; ?>
</div>



