<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class MediaGallery_Model_Base_Media extends Doctrine_Record
{
  public function setTableDefinition()
  {
    $this->setTableName('media');
    $this->hasColumn('id', 'integer', 11, array('primary' => true, 'autoincrement' => true, 'type' => 'integer', 'length' => '11'));
    $this->hasColumn('media_album_id', 'integer', 11, array('type' => 'integer', 'length' => '11'));
    $this->hasColumn('name', 'string', 100, array('type' => 'string', 'length' => '100'));
    $this->hasColumn('type', 'string', 100, array('type' => 'string', 'length' => '100'));
    $this->hasColumn('caption', 'string', 2147483647, array('type' => 'string', 'length' => '2147483647'));
    $this->hasColumn('thumbnail_file', 'string', 255, array('type' => 'string', 'length' => '255'));
    $this->hasColumn('media_file', 'string', 255, array('type' => 'string', 'length' => '255'));
    $this->hasColumn('orig_file_name', 'string', 255, array('type' => 'string', 'length' => '255'));
    $this->hasColumn('created_at', 'timestamp', 25, array('type' => 'timestamp', 'length' => '25'));
    $this->hasColumn('updated_at', 'timestamp', 25, array('type' => 'timestamp', 'length' => '25'));
  }

  public function setUp()
  {
    $this->hasOne('MediaGallery_Model_Album as Album', array('local' => 'media_album_id','foreign' => 'id'));

    $timestampable0 = new Doctrine_Template_Timestampable(array('created' => array('name' => 'created_at'), 'updated' => array('name' => 'updated_at')));
    $this->actAs($timestampable0);
  }
}
